### ISSUE TITLE
Resetting to invalid mark лаги после проигрывания wav в режиме повторения loop

### ISSUE THREAD

**Issue by dzanis** [vuvk/retard_sound_system#1]
После мелодии birds_mono.wav  сильно лагают мелодии после birdsMono.loop(). Это из-за вывода лога с ошибкой Resetting to invalid mark.У меня комп слабый,может поэтому лаг ощутимый.Если закомментировать вывод в лог то нормально играет. Если просто birdsMono.play() то ошибок нет. https://github.com/vuvk/retard_sound_system/blob/2bb0c3199b1e764a00722a4a6bf903334e4c6a03/src/main/java/com/vuvk/retard_sound_system/SoundBasis.java#L126

**Comment by vuvk** [comment]
Используешь последний код из ветки master или из версии 0.4?
Resetting to invalid mark возникает при каком воспроизведении:
1. из файла
2. из буфера
3. из jar
?

loop() == play(true)
Так что вряд ли ошибка кроется здесь

**Comment by dzanis** [comment]
Из jar, а из файловой нормально проигрывает.Ошибка только когда waw проигрывает через loop(). Навено нечего с этим заморачиваться,потому что комп тупит.До этого были странности с запуском,если двумя кликами  jar файл запустить то мелодия не играла,а при запуске из консоли играла.К тому же я из eclpse собираю,тоже может что не так

**Comment by vuvk** [comment]
По идее сборкой занимается система сборки maven и IDE тут никакой особой роли не играет. Попробуй скачать последние обновления из репозитория (git pull). Сегодня накидал множество оптимизаций и исправлений, включая разгрузку процессора, а то я и не заметил как эта система грузит компухтер. Движок стал работать лучше

**Comment by dzanis** [comment]
Скачал последнее обновление, всё нормально проигрывает,ошибок нет.Спасибо.
